#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLichVietNam.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DuLichViet")]
	public partial class DbDuLichVietDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertTTKHACHHANG(TTKHACHHANG instance);
    partial void UpdateTTKHACHHANG(TTKHACHHANG instance);
    partial void DeleteTTKHACHHANG(TTKHACHHANG instance);
    partial void InsertCHITIETDAT(CHITIETDAT instance);
    partial void UpdateCHITIETDAT(CHITIETDAT instance);
    partial void DeleteCHITIETDAT(CHITIETDAT instance);
    partial void InsertDIADIEM(DIADIEM instance);
    partial void UpdateDIADIEM(DIADIEM instance);
    partial void DeleteDIADIEM(DIADIEM instance);
    partial void InsertKHACHSAN(KHACHSAN instance);
    partial void UpdateKHACHSAN(KHACHSAN instance);
    partial void DeleteKHACHSAN(KHACHSAN instance);
    partial void InsertPHUONGTIEN(PHUONGTIEN instance);
    partial void UpdatePHUONGTIEN(PHUONGTIEN instance);
    partial void DeletePHUONGTIEN(PHUONGTIEN instance);
    partial void InsertPTTHANHTOAN(PTTHANHTOAN instance);
    partial void UpdatePTTHANHTOAN(PTTHANHTOAN instance);
    partial void DeletePTTHANHTOAN(PTTHANHTOAN instance);
    partial void InsertTINTUC(TINTUC instance);
    partial void UpdateTINTUC(TINTUC instance);
    partial void DeleteTINTUC(TINTUC instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    #endregion
		
		public DbDuLichVietDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DuLichVietConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDuLichVietDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDuLichVietDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDuLichVietDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDuLichVietDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<TTKHACHHANG> TTKHACHHANGs
		{
			get
			{
				return this.GetTable<TTKHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDAT> CHITIETDATs
		{
			get
			{
				return this.GetTable<CHITIETDAT>();
			}
		}
		
		public System.Data.Linq.Table<DIADIEM> DIADIEMs
		{
			get
			{
				return this.GetTable<DIADIEM>();
			}
		}
		
		public System.Data.Linq.Table<KHACHSAN> KHACHSANs
		{
			get
			{
				return this.GetTable<KHACHSAN>();
			}
		}
		
		public System.Data.Linq.Table<KS_DIADIEM> KS_DIADIEMs
		{
			get
			{
				return this.GetTable<KS_DIADIEM>();
			}
		}
		
		public System.Data.Linq.Table<PHUONGTIEN> PHUONGTIENs
		{
			get
			{
				return this.GetTable<PHUONGTIEN>();
			}
		}
		
		public System.Data.Linq.Table<PTTHANHTOAN> PTTHANHTOANs
		{
			get
			{
				return this.GetTable<PTTHANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<TINTUC> TINTUCs
		{
			get
			{
				return this.GetTable<TINTUC>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PassAdmin;
		
		private string _HoTen;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPassAdminChanging(string value);
    partial void OnPassAdminChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdmin", DbType="VarChar(50)")]
		public string PassAdmin
		{
			get
			{
				return this._PassAdmin;
			}
			set
			{
				if ((this._PassAdmin != value))
				{
					this.OnPassAdminChanging(value);
					this.SendPropertyChanging();
					this._PassAdmin = value;
					this.SendPropertyChanged("PassAdmin");
					this.OnPassAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTKHACHHANG")]
	public partial class TTKHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HotenKH;
		
		private string _Email;
		
		private string _SDT;
		
		private string _DiaChiKH;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private EntitySet<CHITIETDAT> _CHITIETDATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHotenKHChanging(string value);
    partial void OnHotenKHChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiKHChanging(string value);
    partial void OnDiaChiKHChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    #endregion
		
		public TTKHACHHANG()
		{
			this._CHITIETDATs = new EntitySet<CHITIETDAT>(new Action<CHITIETDAT>(this.attach_CHITIETDATs), new Action<CHITIETDAT>(this.detach_CHITIETDATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotenKH", DbType="NVarChar(50)")]
		public string HotenKH
		{
			get
			{
				return this._HotenKH;
			}
			set
			{
				if ((this._HotenKH != value))
				{
					this.OnHotenKHChanging(value);
					this.SendPropertyChanging();
					this._HotenKH = value;
					this.SendPropertyChanged("HotenKH");
					this.OnHotenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKH", DbType="NVarChar(200)")]
		public string DiaChiKH
		{
			get
			{
				return this._DiaChiKH;
			}
			set
			{
				if ((this._DiaChiKH != value))
				{
					this.OnDiaChiKHChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKH = value;
					this.SendPropertyChanged("DiaChiKH");
					this.OnDiaChiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTKHACHHANG_CHITIETDAT", Storage="_CHITIETDATs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<CHITIETDAT> CHITIETDATs
		{
			get
			{
				return this._CHITIETDATs;
			}
			set
			{
				this._CHITIETDATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.TTKHACHHANG = this;
		}
		
		private void detach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.TTKHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDAT")]
	public partial class CHITIETDAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDat;
		
		private int _MaTour;
		
		private int _MaKH;
		
		private System.Nullable<int> _MaThanhToan;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private string _SoLuong;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private System.Nullable<System.DateTime> _NgayDi;
		
		private EntityRef<TTKHACHHANG> _TTKHACHHANG;
		
		private EntityRef<PTTHANHTOAN> _PTTHANHTOAN;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDatChanging(int value);
    partial void OnMaDatChanged();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMaThanhToanChanging(System.Nullable<int> value);
    partial void OnMaThanhToanChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnSoLuongChanging(string value);
    partial void OnSoLuongChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    partial void OnNgayDiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDiChanged();
    #endregion
		
		public CHITIETDAT()
		{
			this._TTKHACHHANG = default(EntityRef<TTKHACHHANG>);
			this._PTTHANHTOAN = default(EntityRef<PTTHANHTOAN>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDat", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDat
		{
			get
			{
				return this._MaDat;
			}
			set
			{
				if ((this._MaDat != value))
				{
					this.OnMaDatChanging(value);
					this.SendPropertyChanging();
					this._MaDat = value;
					this.SendPropertyChanged("MaDat");
					this.OnMaDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Int NOT NULL")]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._TTKHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhToan", DbType="Int")]
		public System.Nullable<int> MaThanhToan
		{
			get
			{
				return this._MaThanhToan;
			}
			set
			{
				if ((this._MaThanhToan != value))
				{
					if (this._PTTHANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MaThanhToan = value;
					this.SendPropertyChanged("MaThanhToan");
					this.OnMaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(50)")]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this.OnNgayDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDi = value;
					this.SendPropertyChanged("NgayDi");
					this.OnNgayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTKHACHHANG_CHITIETDAT", Storage="_TTKHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public TTKHACHHANG TTKHACHHANG
		{
			get
			{
				return this._TTKHACHHANG.Entity;
			}
			set
			{
				TTKHACHHANG previousValue = this._TTKHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._TTKHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TTKHACHHANG.Entity = null;
						previousValue.CHITIETDATs.Remove(this);
					}
					this._TTKHACHHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDATs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("TTKHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PTTHANHTOAN_CHITIETDAT", Storage="_PTTHANHTOAN", ThisKey="MaThanhToan", OtherKey="MaThanhToan", IsForeignKey=true)]
		public PTTHANHTOAN PTTHANHTOAN
		{
			get
			{
				return this._PTTHANHTOAN.Entity;
			}
			set
			{
				PTTHANHTOAN previousValue = this._PTTHANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._PTTHANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PTTHANHTOAN.Entity = null;
						previousValue.CHITIETDATs.Remove(this);
					}
					this._PTTHANHTOAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETDATs.Add(this);
						this._MaThanhToan = value.MaThanhToan;
					}
					else
					{
						this._MaThanhToan = default(Nullable<int>);
					}
					this.SendPropertyChanged("PTTHANHTOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CHITIETDAT", Storage="_TOUR", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.CHITIETDATs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.CHITIETDATs.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(int);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADIEM")]
	public partial class DIADIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDD;
		
		private string _TenDD;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDChanging(int value);
    partial void OnMaDDChanged();
    partial void OnTenDDChanging(string value);
    partial void OnTenDDChanged();
    #endregion
		
		public DIADIEM()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDD", DbType="NVarChar(50)")]
		public string TenDD
		{
			get
			{
				return this._TenDD;
			}
			set
			{
				if ((this._TenDD != value))
				{
					this.OnTenDDChanging(value);
					this.SendPropertyChanging();
					this._TenDD = value;
					this.SendPropertyChanged("TenDD");
					this.OnTenDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_TOUR", Storage="_TOURs", ThisKey="MaDD", OtherKey="MaDD")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHSAN")]
	public partial class KHACHSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKS;
		
		private string _TenKS;
		
		private string _TongQuan;
		
		private string _DacDiem;
		
		private System.Nullable<int> _MaPLKS;
		
		private string _AnhKS;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(int value);
    partial void OnMaKSChanged();
    partial void OnTenKSChanging(string value);
    partial void OnTenKSChanged();
    partial void OnTongQuanChanging(string value);
    partial void OnTongQuanChanged();
    partial void OnDacDiemChanging(string value);
    partial void OnDacDiemChanged();
    partial void OnMaPLKSChanging(System.Nullable<int> value);
    partial void OnMaPLKSChanged();
    partial void OnAnhKSChanging(string value);
    partial void OnAnhKSChanged();
    #endregion
		
		public KHACHSAN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKS", DbType="NVarChar(50)")]
		public string TenKS
		{
			get
			{
				return this._TenKS;
			}
			set
			{
				if ((this._TenKS != value))
				{
					this.OnTenKSChanging(value);
					this.SendPropertyChanging();
					this._TenKS = value;
					this.SendPropertyChanged("TenKS");
					this.OnTenKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongQuan", DbType="NVarChar(MAX)")]
		public string TongQuan
		{
			get
			{
				return this._TongQuan;
			}
			set
			{
				if ((this._TongQuan != value))
				{
					this.OnTongQuanChanging(value);
					this.SendPropertyChanging();
					this._TongQuan = value;
					this.SendPropertyChanged("TongQuan");
					this.OnTongQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DacDiem", DbType="NVarChar(30)")]
		public string DacDiem
		{
			get
			{
				return this._DacDiem;
			}
			set
			{
				if ((this._DacDiem != value))
				{
					this.OnDacDiemChanging(value);
					this.SendPropertyChanging();
					this._DacDiem = value;
					this.SendPropertyChanged("DacDiem");
					this.OnDacDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPLKS", DbType="Int")]
		public System.Nullable<int> MaPLKS
		{
			get
			{
				return this._MaPLKS;
			}
			set
			{
				if ((this._MaPLKS != value))
				{
					this.OnMaPLKSChanging(value);
					this.SendPropertyChanging();
					this._MaPLKS = value;
					this.SendPropertyChanged("MaPLKS");
					this.OnMaPLKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhKS", DbType="VarChar(50)")]
		public string AnhKS
		{
			get
			{
				return this._AnhKS;
			}
			set
			{
				if ((this._AnhKS != value))
				{
					this.OnAnhKSChanging(value);
					this.SendPropertyChanging();
					this._AnhKS = value;
					this.SendPropertyChanged("AnhKS");
					this.OnAnhKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_TOURs", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KS_DIADIEM")]
	public partial class KS_DIADIEM
	{
		
		private int _MaPLKS;
		
		private string _DiaDiemDuLich;
		
		public KS_DIADIEM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPLKS", DbType="Int NOT NULL")]
		public int MaPLKS
		{
			get
			{
				return this._MaPLKS;
			}
			set
			{
				if ((this._MaPLKS != value))
				{
					this._MaPLKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemDuLich", DbType="NVarChar(100)")]
		public string DiaDiemDuLich
		{
			get
			{
				return this._DiaDiemDuLich;
			}
			set
			{
				if ((this._DiaDiemDuLich != value))
				{
					this._DiaDiemDuLich = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUONGTIEN")]
	public partial class PHUONGTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPT;
		
		private string _LoaiPT;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTChanging(int value);
    partial void OnMaPTChanged();
    partial void OnLoaiPTChanging(string value);
    partial void OnLoaiPTChanged();
    #endregion
		
		public PHUONGTIEN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPT
		{
			get
			{
				return this._MaPT;
			}
			set
			{
				if ((this._MaPT != value))
				{
					this.OnMaPTChanging(value);
					this.SendPropertyChanging();
					this._MaPT = value;
					this.SendPropertyChanged("MaPT");
					this.OnMaPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPT", DbType="NVarChar(50)")]
		public string LoaiPT
		{
			get
			{
				return this._LoaiPT;
			}
			set
			{
				if ((this._LoaiPT != value))
				{
					this.OnLoaiPTChanging(value);
					this.SendPropertyChanging();
					this._LoaiPT = value;
					this.SendPropertyChanged("LoaiPT");
					this.OnLoaiPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTIEN_TOUR", Storage="_TOURs", ThisKey="MaPT", OtherKey="MaPT")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTIEN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PTTHANHTOAN")]
	public partial class PTTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThanhToan;
		
		private string _TenPT;
		
		private EntitySet<CHITIETDAT> _CHITIETDATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhToanChanging(int value);
    partial void OnMaThanhToanChanged();
    partial void OnTenPTChanging(string value);
    partial void OnTenPTChanged();
    #endregion
		
		public PTTHANHTOAN()
		{
			this._CHITIETDATs = new EntitySet<CHITIETDAT>(new Action<CHITIETDAT>(this.attach_CHITIETDATs), new Action<CHITIETDAT>(this.detach_CHITIETDATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhToan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaThanhToan
		{
			get
			{
				return this._MaThanhToan;
			}
			set
			{
				if ((this._MaThanhToan != value))
				{
					this.OnMaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MaThanhToan = value;
					this.SendPropertyChanged("MaThanhToan");
					this.OnMaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPT", DbType="NVarChar(20)")]
		public string TenPT
		{
			get
			{
				return this._TenPT;
			}
			set
			{
				if ((this._TenPT != value))
				{
					this.OnTenPTChanging(value);
					this.SendPropertyChanging();
					this._TenPT = value;
					this.SendPropertyChanged("TenPT");
					this.OnTenPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PTTHANHTOAN_CHITIETDAT", Storage="_CHITIETDATs", ThisKey="MaThanhToan", OtherKey="MaThanhToan")]
		public EntitySet<CHITIETDAT> CHITIETDATs
		{
			get
			{
				return this._CHITIETDATs;
			}
			set
			{
				this._CHITIETDATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.PTTHANHTOAN = this;
		}
		
		private void detach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.PTTHANHTOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINTUC")]
	public partial class TINTUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private string _TenTT;
		
		private string _NoiDung;
		
		private string _Anhbia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnTenTTChanging(string value);
    partial void OnTenTTChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    #endregion
		
		public TINTUC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="NVarChar(200)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this.OnTenTTChanging(value);
					this.SendPropertyChanging();
					this._TenTT = value;
					this.SendPropertyChanged("TenTT");
					this.OnTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="VarChar(50)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private string _TenTour;
		
		private string _ThoiGian;
		
		private string _XuatPhat;
		
		private System.Nullable<decimal> _GiaTour;
		
		private string _Mota;
		
		private string _Anhbia;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _MaPT;
		
		private System.Nullable<int> _MaKS;
		
		private System.Nullable<int> _MaDD;
		
		private string _LoTrinh;
		
		private EntitySet<CHITIETDAT> _CHITIETDATs;
		
		private EntityRef<DIADIEM> _DIADIEM;
		
		private EntityRef<KHACHSAN> _KHACHSAN;
		
		private EntityRef<PHUONGTIEN> _PHUONGTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnTenTourChanging(string value);
    partial void OnTenTourChanged();
    partial void OnThoiGianChanging(string value);
    partial void OnThoiGianChanged();
    partial void OnXuatPhatChanging(string value);
    partial void OnXuatPhatChanged();
    partial void OnGiaTourChanging(System.Nullable<decimal> value);
    partial void OnGiaTourChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnMaPTChanging(System.Nullable<int> value);
    partial void OnMaPTChanged();
    partial void OnMaKSChanging(System.Nullable<int> value);
    partial void OnMaKSChanged();
    partial void OnMaDDChanging(System.Nullable<int> value);
    partial void OnMaDDChanged();
    partial void OnLoTrinhChanging(string value);
    partial void OnLoTrinhChanged();
    #endregion
		
		public TOUR()
		{
			this._CHITIETDATs = new EntitySet<CHITIETDAT>(new Action<CHITIETDAT>(this.attach_CHITIETDATs), new Action<CHITIETDAT>(this.detach_CHITIETDATs));
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._KHACHSAN = default(EntityRef<KHACHSAN>);
			this._PHUONGTIEN = default(EntityRef<PHUONGTIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTour", DbType="NVarChar(100)")]
		public string TenTour
		{
			get
			{
				return this._TenTour;
			}
			set
			{
				if ((this._TenTour != value))
				{
					this.OnTenTourChanging(value);
					this.SendPropertyChanging();
					this._TenTour = value;
					this.SendPropertyChanged("TenTour");
					this.OnTenTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(50)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatPhat", DbType="NVarChar(50)")]
		public string XuatPhat
		{
			get
			{
				return this._XuatPhat;
			}
			set
			{
				if ((this._XuatPhat != value))
				{
					this.OnXuatPhatChanging(value);
					this.SendPropertyChanging();
					this._XuatPhat = value;
					this.SendPropertyChanged("XuatPhat");
					this.OnXuatPhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTour", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTour
		{
			get
			{
				return this._GiaTour;
			}
			set
			{
				if ((this._GiaTour != value))
				{
					this.OnGiaTourChanging(value);
					this.SendPropertyChanging();
					this._GiaTour = value;
					this.SendPropertyChanged("GiaTour");
					this.OnGiaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="VarChar(50)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPT", DbType="Int")]
		public System.Nullable<int> MaPT
		{
			get
			{
				return this._MaPT;
			}
			set
			{
				if ((this._MaPT != value))
				{
					if (this._PHUONGTIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTChanging(value);
					this.SendPropertyChanging();
					this._MaPT = value;
					this.SendPropertyChanged("MaPT");
					this.OnMaPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="Int")]
		public System.Nullable<int> MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KHACHSAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Int")]
		public System.Nullable<int> MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					if (this._DIADIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoTrinh", DbType="NVarChar(MAX)")]
		public string LoTrinh
		{
			get
			{
				return this._LoTrinh;
			}
			set
			{
				if ((this._LoTrinh != value))
				{
					this.OnLoTrinhChanging(value);
					this.SendPropertyChanging();
					this._LoTrinh = value;
					this.SendPropertyChanged("LoTrinh");
					this.OnLoTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CHITIETDAT", Storage="_CHITIETDATs", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<CHITIETDAT> CHITIETDATs
		{
			get
			{
				return this._CHITIETDATs;
			}
			set
			{
				this._CHITIETDATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIADIEM_TOUR", Storage="_DIADIEM", ThisKey="MaDD", OtherKey="MaDD", IsForeignKey=true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value) 
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaDD = value.MaDD;
					}
					else
					{
						this._MaDD = default(Nullable<int>);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_KHACHSAN", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KHACHSAN KHACHSAN
		{
			get
			{
				return this._KHACHSAN.Entity;
			}
			set
			{
				KHACHSAN previousValue = this._KHACHSAN.Entity;
				if (((previousValue != value) 
							|| (this._KHACHSAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHSAN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._KHACHSAN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHSAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTIEN_TOUR", Storage="_PHUONGTIEN", ThisKey="MaPT", OtherKey="MaPT", IsForeignKey=true)]
		public PHUONGTIEN PHUONGTIEN
		{
			get
			{
				return this._PHUONGTIEN.Entity;
			}
			set
			{
				PHUONGTIEN previousValue = this._PHUONGTIEN.Entity;
				if (((previousValue != value) 
							|| (this._PHUONGTIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUONGTIEN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._PHUONGTIEN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaPT = value.MaPT;
					}
					else
					{
						this._MaPT = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHUONGTIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_CHITIETDATs(CHITIETDAT entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
}
#pragma warning restore 1591
